### ISSUE TITLE
Handling the packages with no code

### ISSUE THREAD

**Issue by maksymiuks** [Genentech/covtracer#20]
Currently covtracer cannot handle the packages that are empty ie. without any code. Although it my sound silly these are perfectly valid R packages that could be for instance an interface for other packages (just reexported packages) or a form of storage for external files. Currently running `covtracer::test_trace_df(cov)` for said packages results in a following error:

```
Error in coverage_check_has_recorded_tests(x) : 
  Coverage object does not include recorded test information.

  Expecting non-null `cov[[n]]$tests` for each trace

  Ensure `options(covr.record_tests = TRUE)` was set during coverage execution.
```

as it probably is a hard to imagine use case that will rarely occur, especially that such packages does not need covtracer, I suggests  to assure `covtracer` can work with those, to not break any automated process that might use `covtracer` and might be fed with weird packages.

To reproduce said problem, try to build test_trace_df for [assertive](https://cran.r-project.org/web/packages/assertive/index.html) CRAN package.

**Comment by dgkf** [comment]
Thanks @maksymiuks - This is definitely an interesting edge case. 

`cov[[n]]$tests` (a matrix itemizing test calls that hit trace `n`) will be `NULL` if the trace is never executed. Upon first execution, `$tests` is instantiated with a 0-row matrix. However, if the package contains no code, then `n` == 0, and when we use this heuristic to try to determine whether tests were captured, it looks as though the test-trace matrices weren't captured.

I think a check for `n` > 0 should resolve this edge case:

https://github.com/Genentech/covtracer/blob/0fba3abb1f0fe96c5658b40150492aa9aa032efb/R/test_trace_df.R#L115-L129
```diff
-  if (!any(has_rec_tests)) {
+  if (length(has_rec_tests) > 0L && !any(has_rec_tests)) {
```

I'm not sure how this will affect the downstream processing - there might be downstream code that assumes that there are at least some traces that were recorded.
