### ISSUE TITLE
Reexports crash the covtracer

### ISSUE THREAD

**Issue by maksymiuks** [Genentech/covtracer#27]
While using the `covtracer` package, I've encountered a bug that crashes the `test_trace_df.coverage` function if the passes coverage file was built for a package that has both exports and reexports. I'll try to give a detailed look at the issue based on the example of a `geepack` package (https://cran.r-project.org/web/packages/geepack/index.html). 

To begin with, let's starts with the actual place where the error occurs, it is in the `match_containing_srcrefs` helper (https://github.com/Genentech/covtracer/blob/main/R/srcref_df.R#L274) and it is thrown because of the unexpected NA passed to `Position` function. That NA comes from the `rdf` object defined here https://github.com/Genentech/covtracer/blob/main/R/srcref_df.R#L262. Here is how problematic part of the data frame looks like:

```
                  name                                                                                                        srcfile line1 byte1 line2
24 print.summary.geese /private/var/folders/bh/g3p3b4sn0lx9ml5kr20bbq3c0000gp/T/RtmpWMzIhZ/R.INSTALL112c04f3c5fbb/geepack/R/summary.R    83    24   117
33                 %>%                                                                                                           <NA>    NA    NA    NA
34                tidy                                                                                                           <NA>    NA    NA    NA
   byte2 col1 col2 parsed1 parsed2
24     1   24    1    3003    3037
33    NA   NA   NA      NA      NA
34    NA   NA   NA      NA      NA
```

It is understandable why do we have NA there, `%>%` and `tidy` are reexports so there is no source for them within the package. 

On the question how is that situation different from the assertive pacakge, for which we can successfully execute this function, the answer is this line https://github.com/Genentech/covtracer/blob/main/R/srcref_df.R#L271. assertive has only reexports so the `ldf` object has 0 rows and we never enter that loop, meaning, w never touch line 274 that is crashing the function.

Last but not least I want to clarify how the stack looks like there:

`test_trace_df.coverage` -> `join_on_containing_srcrefs` (https://github.com/Genentech/covtracer/blob/main/R/test_trace_df.R#L92-L96) -> `match_containing_srcrefs` (https://github.com/Genentech/covtracer/blob/main/R/srcref_df.R#L342)

I'm pretty sure the issues come from that reexports thingy, looking at the objects that are passed downstream in `test_trace_df.coverage`, I just don't feel experienced enough to solve this issue on my own.

**Comment by dgkf** [comment]
Thanks @maksymiuks - sounds like a new consideration now that we're handling srcref-less traces (via reexports). Thanks for raising this. 

I think the solution will end up handling `NA`s specifically. I'll try to get something together and also add some tests for this scenario.

**Comment by dgkf** [comment]
I've been able to reproduce the issue and will try to isolate a test case to make sure this issue doesn't sneak up on us again.
