### ISSUE TITLE
srcrefs.MethodDefinition tries to assign attribute to a NULL value

### ISSUE THREAD

**Issue by maksymiuks** [Genentech/covtracer#30]
During my exploring of covtracer package (this time with the `VGAM` package), I've discovered a bug causing the `covtracer:::test_trace_df.coverage` to crash with the error saying (translation) 

```
Error in attr(objs[[i]], "namespace") <- ns 
attempt to set an attribute on NULL
```
Here is the problematic line: https://github.com/Genentech/covtracer/blob/main/R/srcrefs.R#L119

For reasons yet unknown for me, the `objs[[1]]` for some reason appears to be a NULL meaning we cannot set an attribute to it.

I've tried solving it by adding simple if that would call `next()` if `objs[[1]]` is null, but then the resulting data.frame is flooded with NA values and warnings 

```
'if (!is_exported) return(NA_character_)':
 the condition has length > 1 and only the first element will be used
```

I'll try to investigate where the problem comes from, but would love to hear your opinion and insigths @dgkf

**Comment by dgkf** [comment]
Thanks for the sleuthing on this one, @maksymiuks - I think I was able to drill down into what was going wrong.

**Comment by maksymiuks** [comment]
Fixed by https://github.com/Genentech/covtracer/pull/31 thanks!
